// =============================================================================
// Los veredictos de HE1, HR y HS1 ANTES de feature-26 (código de 3f5b662), para
// el test de cierre `sin-cerramientos.test.ts`. Generado una vez con el mismo
// recorrido que el test; no se edita a mano. Cada valor: el veredicto global y
// los elementos («id» si cumple, «id=fail» o «id=dato» si no).
// =============================================================================

export const VEREDICTOS_ANTES: Record<string, string> = {
  "he1/unifamiliar/asi/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/asi/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/unifamiliar/asi/demo": "ok · tabiqueria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/asi/ld65": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/asi/ld70": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/unifamiliar/asi/ld75a": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/unifamiliar/asi/iv": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/asi/i": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/asi/ii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/asi/iii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/asi/sin": "ok · terreno=dato suelo-pb dren-suelo bombeo fachada cubierta",
  "he1/unifamiliar/plana_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/unifamiliar/plana_transitable/demo": "ok · tabiqueria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/plana_transitable/ld65": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/plana_transitable/ld70": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/unifamiliar/plana_transitable/ld75a": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/unifamiliar/plana_transitable/iv": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_transitable/i": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_transitable/ii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_transitable/iii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_transitable/sin": "ok · terreno=dato suelo-pb dren-suelo bombeo fachada cubierta",
  "he1/unifamiliar/plana_no_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/plana_no_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/unifamiliar/plana_no_transitable/demo": "ok · tabiqueria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/plana_no_transitable/ld65": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/plana_no_transitable/ld70": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/unifamiliar/plana_no_transitable/ld75a": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/unifamiliar/plana_no_transitable/iv": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_no_transitable/i": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_no_transitable/ii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_no_transitable/iii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/plana_no_transitable/sin": "ok · terreno=dato suelo-pb dren-suelo bombeo fachada cubierta",
  "he1/unifamiliar/inclinada/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/unifamiliar/inclinada/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/unifamiliar/inclinada/demo": "ok · tabiqueria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/inclinada/ld65": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/unifamiliar/inclinada/ld70": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/unifamiliar/inclinada/ld75a": "fail · tabiqueria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/unifamiliar/inclinada/iv": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/inclinada/i": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/inclinada/ii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/inclinada/iii": "ok · terreno=dato suelo-pb fachada cubierta",
  "hs1/unifamiliar/inclinada/sin": "ok · terreno=dato suelo-pb dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar/asi/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/asi/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar/asi/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/asi/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/asi/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar/asi/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar/asi/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/asi/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/asi/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/asi/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/asi/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar/plana_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar/plana_transitable/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/plana_transitable/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/plana_transitable/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar/plana_transitable/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar/plana_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar/plana_no_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/plana_no_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar/plana_no_transitable/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/plana_no_transitable/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/plana_no_transitable/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar/plana_no_transitable/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar/plana_no_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_no_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_no_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_no_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/plana_no_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar/inclinada/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar/inclinada/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar/inclinada/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/inclinada/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar/inclinada/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar/inclinada/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar/inclinada/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/inclinada/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/inclinada/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/inclinada/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar/inclinada/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar_locales/asi/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/asi/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar_locales/asi/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/asi/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/asi/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/asi/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar_locales/asi/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/asi/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/asi/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/asi/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/asi/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar_locales/plana_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar_locales/plana_transitable/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/plana_transitable/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/plana_transitable/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/plana_transitable/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar_locales/plana_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar_locales/plana_no_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/plana_no_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar_locales/plana_no_transitable/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/plana_no_transitable/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/plana_no_transitable/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/plana_no_transitable/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar_locales/plana_no_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_no_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_no_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_no_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/plana_no_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/plurifamiliar_locales/inclinada/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/plurifamiliar_locales/inclinada/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/plurifamiliar_locales/inclinada/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/inclinada/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/inclinada/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/plurifamiliar_locales/inclinada/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/plurifamiliar_locales/inclinada/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/inclinada/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/inclinada/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/inclinada/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/plurifamiliar_locales/inclinada/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/oficinas/asi/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/asi/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/asi/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/asi/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/oficinas/asi/demo": "ok · medianeria fachada-estancias cubierta instalaciones=dato",
  "hr/oficinas/asi/ld65": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/asi/ld70": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/asi/ld75a": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/oficinas/asi/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/asi/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/asi/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/asi/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/asi/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/oficinas/plana_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/oficinas/plana_transitable/demo": "ok · medianeria fachada-estancias cubierta instalaciones=dato",
  "hr/oficinas/plana_transitable/ld65": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/plana_transitable/ld70": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/plana_transitable/ld75a": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/oficinas/plana_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/oficinas/plana_no_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/plana_no_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/oficinas/plana_no_transitable/demo": "ok · medianeria fachada-estancias cubierta instalaciones=dato",
  "hr/oficinas/plana_no_transitable/ld65": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/plana_no_transitable/ld70": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/plana_no_transitable/ld75a": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/oficinas/plana_no_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_no_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_no_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_no_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/plana_no_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/oficinas/inclinada/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/oficinas/inclinada/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/oficinas/inclinada/demo": "ok · medianeria fachada-estancias cubierta instalaciones=dato",
  "hr/oficinas/inclinada/ld65": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/inclinada/ld70": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hr/oficinas/inclinada/ld75a": "fail · medianeria fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/oficinas/inclinada/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/inclinada/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/inclinada/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/inclinada/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/oficinas/inclinada/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/demo/asi/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/asi/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/asi/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/asi/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/demo/asi/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/demo/asi/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/demo/asi/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/demo/asi/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/demo/asi/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/asi/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/asi/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/asi/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/asi/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/demo/plana_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/demo/plana_transitable/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/demo/plana_transitable/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/demo/plana_transitable/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/demo/plana_transitable/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/demo/plana_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/demo/plana_no_transitable/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/plana_no_transitable/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/demo/plana_no_transitable/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/demo/plana_no_transitable/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/demo/plana_no_transitable/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/demo/plana_no_transitable/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/demo/plana_no_transitable/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_no_transitable/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_no_transitable/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_no_transitable/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/plana_no_transitable/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
  "he1/demo/inclinada/caceres/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/caceres/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/caceres/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/caceres/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/inclinada/burgos/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/burgos/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/burgos/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/burgos/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "he1/demo/inclinada/sin/habitual": "ok · fachada cubierta suelo ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/sin/finos": "fail · fachada=fail cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/sin/justos": "fail · fachada cubierta=fail suelo=fail ventanas superficial intersticial hulc=fuera",
  "he1/demo/inclinada/sin/medios": "fail · fachada=fail cubierta suelo ventanas=fail superficial intersticial hulc=fuera",
  "hr/demo/inclinada/demo": "ok · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios fachada-estancias cubierta instalaciones=dato",
  "hr/demo/inclinada/ld65": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias cubierta instalaciones=dato",
  "hr/demo/inclinada/ld70": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hr/demo/inclinada/ld75a": "fail · tabiqueria separacion puerta=dato ascensor forjado-viviendas forjado-comun forjado-actividad medianeria fachada-dormitorios=fail fachada-estancias=fail cubierta instalaciones=dato",
  "hs1/demo/inclinada/iv": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/inclinada/i": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/inclinada/ii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/inclinada/iii": "ok · terreno=dato muro suelo-sotano fachada cubierta",
  "hs1/demo/inclinada/sin": "ok · terreno=dato muro suelo-sotano dren-muro dren-suelo bombeo fachada cubierta",
};
